# Generated by Django 3.1.1 on 2021-09-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
